'use strict';
const slides=window.REPORT, $=id=>document.getElementById(id),asset=name=>window.ASSETS?.[name]||'assets/'+name;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let current=0,zoom=1;
function imageMarkup(name,label){return `<img src="${asset(name)}" alt="${esc(label)}" data-image="${esc(name)}" tabindex="0" role="button" aria-label="放大：${esc(label)}">`;}
function original(s){return `<article class="slide original"><div class="visual">${imageMarkup(s.image,s.title)}</div><section class="explain"><div><h1>${esc(s.title)}</h1><div class="source">${esc(s.source)}</div></div><p>${esc(s.text)}</p></section></article>`;}
function project(s){return `<article class="slide project"><header class="project-head"><div><p class="eyebrow">同类型项目业绩展示 &nbsp; / &nbsp; ${esc(s.tag)}</p><h1>${esc(s.title)}</h1></div><div class="project-name">${esc(s.section)}</div></header><div class="project-body"><div class="picture-zone"><div class="picture">${imageMarkup(s.image,s.title)}<span class="zoom-label">点击放大图面 ＋</span></div>${s.extra?`<div class="gallery"><button class="active" data-gallery="${s.image}">主要图面</button><button data-gallery="${s.extra[0]}">${esc(s.extra[1])}</button></div>`:''}</div><section class="project-copy"><div class="rule"></div><p class="narrative">${esc(s.text)}</p><div class="metrics">${s.metrics.map((m,i)=>`<div class="metric" style="animation-delay:${i*.08}s"><b>${esc(m[0])}</b><span>${esc(m[1])}</span></div>`).join('')}</div><div class="source">资料依据<br>${esc(s.source)}</div></section></div></article>`;}
function target(name){if(name.includes('丹棱'))return 27;if(name.includes('广元'))return 32;if(name.includes('中欧'))return 17;if(name.includes('现代城际'))return 22;return null;}
function overview(s){let n=0;const groups=[['银行',s.projects.filter(p=>p.type==='银行')],['光伏与能源',s.projects.filter(p=>['光伏','能源站'].includes(p.type))],['仓储物流',s.projects.filter(p=>!['银行','光伏','能源站'].includes(p.type))]];return `<article class="slide overview"><header class="overview-top"><div><p class="eyebrow">SELECTED EXPERIENCE</p><h1>${esc(s.title)}</h1><p>${esc(s.subtitle)}</p></div><div class="overview-number">21<span>项业绩</span></div></header><div class="project-columns">${groups.map(([name,items])=>`<section class="project-column"><h2>${name}<span>${String(items.length).padStart(2,'0')} PROJECTS</span></h2>${items.map(p=>{const t=target(p.name);n++;return `<${t!==null?'a':'div'} ${t!==null?`href="#${t+1}"`:''} class="project-row ${t!==null?'linked':''}"><span class="num">${String(n).padStart(2,'0')}</span><span><span class="name">${esc(p.name)}</span><span class="type">${esc(p.type)}</span></span></${t!==null?'a':'div'}>`}).join('')}</section>`).join('')}</div><div class="overview-bottom"><p>22条记录合并为21个项目；丹棱农商行方案与施工图设计合并。<br>橙色箭头项目可点击进入专题。</p><div class="source">${esc(s.source)}</div></div></article>`;}
function render(){const s=slides[current];$('stage').innerHTML=s.kind==='original'?original(s):s.kind==='overview'?overview(s):project(s);$('stage').scrollTop=0;$('section').textContent=s.section;$('page').value=current+1;$('total').textContent='/ '+slides.length;$('page').max=slides.length;$('progress').style.width=(current+1)/slides.length*100+'%';$('prev').disabled=current===0;$('next').disabled=current===slides.length-1;document.title=`${current+1} · ${s.title} | 川建院业绩汇报`;document.querySelectorAll('[data-image]').forEach(el=>{el.addEventListener('click',()=>openImage(el.dataset.image,el.alt));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openImage(el.dataset.image,el.alt)}})});document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>{document.querySelector('.picture').innerHTML=imageMarkup(b.dataset.gallery,b.textContent)+'<span class="zoom-label">点击放大图面 ＋</span>';document.querySelectorAll('[data-gallery]').forEach(x=>x.classList.toggle('active',x===b));const im=document.querySelector('.picture img');im.onclick=()=>openImage(im.dataset.image,b.textContent);im.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openImage(im.dataset.image,b.textContent)}};});for(const i of [current-1,current+1])if(slides[i]?.image){const im=new Image();im.src=asset(slides[i].image);}}
function go(i){i=Math.max(0,Math.min(slides.length-1,Number(i)||0));if(i===current)return;location.hash=String(i+1);}
function readHash(){current=Math.max(0,Math.min(slides.length-1,(parseInt(location.hash.slice(1),10)||1)-1));render();}
$('prev').onclick=()=>go(current-1);$('next').onclick=()=>go(current+1);$('page').onchange=e=>go(Number(e.target.value)-1);window.addEventListener('hashchange',readHash);
function full(){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>{});}
$('full').onclick=full;document.addEventListener('fullscreenchange',()=>{$('full').innerHTML=(document.fullscreenElement?'退出全屏':'全屏')+' <kbd>F</kbd>'});
const chapters=[['企业概况',0],['同类型业绩总览',16],['中欧班列',17],['宜宾叙州',22],['丹棱农商行',27],['广元商业银行',32],['原企业简介续篇',37],['数字业务',53],['企业文化',61]];
$('chapters').innerHTML=chapters.map(([t,i])=>`<button data-go="${i}">${t}</button>`).join('');
$('page-list').innerHTML=slides.map((s,i)=>`<button data-go="${i}"><span>${String(i+1).padStart(2,'0')}</span>${esc(s.title)}</button>`).join('');
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{go(Number(b.dataset.go));$('directory').close()});
$('contents').onclick=()=>{document.querySelectorAll('#page-list button').forEach((b,i)=>b.classList.toggle('current',i===current));$('directory').showModal();document.querySelector('#page-list .current')?.scrollIntoView({block:'center'})};
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}}));
function openImage(name,label){zoom=1;$('large-image').src=asset(name);$('large-image').alt=label;$('image-title').textContent=label;applyZoom();$('lightbox').showModal();}
function applyZoom(){const im=$('large-image');im.style.maxWidth=zoom===1?'100%':'none';im.style.maxHeight=zoom===1?'100%':'none';im.style.width=zoom===1?'auto':`${zoom*90}vw`;im.style.height='auto';}
$('zoom-in').onclick=()=>{zoom=Math.min(4,zoom+.5);applyZoom()};$('zoom-out').onclick=()=>{zoom=Math.max(1,zoom-.5);applyZoom()};$('zoom-reset').onclick=()=>{zoom=1;applyZoom()};
document.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA'].includes(document.activeElement.tagName)||(document.activeElement.tagName==='BUTTON'&&e.key===' '))return;if(['ArrowRight','ArrowDown','PageDown',' '].includes(e.key)){e.preventDefault();go(current+1)}else if(['ArrowLeft','ArrowUp','PageUp'].includes(e.key)){e.preventDefault();go(current-1)}else if(e.key==='Home'){e.preventDefault();go(0)}else if(e.key==='End'){e.preventDefault();go(slides.length-1)}else if(e.key.toLowerCase()==='g')$('contents').click();else if(e.key.toLowerCase()==='f')full();});
let start=null;$('stage').addEventListener('touchstart',e=>{start={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:true});$('stage').addEventListener('touchend',e=>{if(!start)return;const x=e.changedTouches[0].clientX-start.x,y=e.changedTouches[0].clientY-start.y;if(Math.abs(x)>75&&Math.abs(x)>Math.abs(y)*2)go(current+(x<0?1:-1));start=null},{passive:true});readHash();

